package com.isb.vega.externalization.generator.xml;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Global {
  public static CharSequence doGenerateGlobal() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<treeTbls>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<treeTbl>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<application>");
    _builder.append("</application>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<presentationOP>");
    _builder.append("</presentationOP>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<version>");
    _builder.append("</version> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<jsp>");
    _builder.append("</jsp>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table>");
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<columns>");
    _builder.append("</columns> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</treeTbl>");
    _builder.newLine();
    _builder.append("</treeTbls>");
    _builder.newLine();
    _builder.append("<mgrTables>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<mgrTable>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<application>");
    _builder.append("</application>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<presentationOP>");
    _builder.append("</presentationOP>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<version>");
    _builder.append("</version> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<jsp>");
    _builder.append("</jsp>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<table>");
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<columns>");
    _builder.append("</columns> ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</mgrTable>");
    _builder.newLine();
    _builder.append("</mgrTables>");
    _builder.newLine();
    _builder.append("<clientArcReferences>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<clientArcRef>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<application>");
    _builder.append("</application>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<presentationOP>");
    _builder.append("</presentationOP>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<version>");
    _builder.append("</version>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<src>");
    _builder.append("</src>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<reference>");
    _builder.append("</reference>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</clientArcRef>");
    _builder.newLine();
    _builder.append("</clientArcReferences>");
    _builder.newLine();
    return _builder;
  }
}
